
version: "3.9"

services:
  db:
    image: postgres:16
    container_name: contabilidad_db
    restart: always
    environment:
      - PORT_BE=${PORT_BE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - contabilidad_net
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: contabilidad_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}

    ports:
      - "${PGADMIN_PORT}:5050"
    depends_on:
      - db
    networks:
      - contabilidad_net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build: ./backend
    container_name: contabilidad_backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - contabilidad_net

  frontend:
    build: ./frontend
    container_name: contabilidad_frontend
    restart: always
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    networks:
      - contabilidad_net

networks:
  contabilidad_net:
    driver: bridge

volumes:
  db_data:
  pgadmin_data:
